### ISSUE TITLE
Replace requirement of typo3-oauth2-client

### ISSUE THREAD

**Issue by hirnschmalz** [xima-media/xima-oauth2-extended#20]
Regarding to https://github.com/waldhacker/ext-oauth2-client/issues/19#issuecomment-2034871999 the extension will not be maintained by to original creator anymore.

Could you change the requirement in composer.json from `"waldhacker/typo3-oauth2-client",` to `in2code/typo3-oauth2-client-fork`?

**Comment by maikschneider** [comment]
Thanks for the feedback @hirnschmalz! Yes, I'm aware of the current situation with the waldhacker repo. I'm still waiting for a response of in2code - if they are added as maintainer, the vendor would not change. 

Could you open a PR with you changes please?

**Comment by maikschneider** [comment]
Thanks, I just tested your PR #22. Unfortunately in2code did not adjust the frontend login for v12. I'll stick to my fork until a stable version of ext-oauth2-client is released.

**Comment by secured** [comment]
is there any news about the situation?

**Comment by maikschneider** [comment]
@secured Unfortunately, the guys from co-stack are not able to create a new release that contains my fixes. I don't get the point of moving to GitLab, changing the vendor name, adding new author names, but not releasing a new version. We need to wait. Maybe I will publish a version since I cannot see a roadmap for a v13 release.

**Comment by hirnschmalz** [comment]
@maikschneider I'm a bit confused, as far as I can see your code was merged into the devlopment branch:

https://gitlab.com/co-stack.com/co-stack.com/typo3-extensions/typo3-oauth2-client/-/commit/49b321f61ae1a001d1802bfdad22c696d9ad564d

Or am I missing something?

**Comment by maikschneider** [comment]
@hirnschmalz Yes, they merged it. But I cannot use it as dependency as long as they are not tagging it.

**Comment by hirnschmalz** [comment]
@maikschneider a OK, I see. But you could require `"co-stack/typo3-oauth2-client": "dev-develop"`. But I agree, since this is a development branch this doesn't seem to be a good idea.

**Comment by maikschneider** [comment]
Requiring "dev-anything" as dependency in a third-party package would force the main project to lower the [minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability). Yeah, this is not a good idea.

I managed to update the oauth-client to v13: We're currently refactoring the tests for real acceptance tests - I think we will release a version by the end of September.

**Comment by hirnschmalz** [comment]
@maikschneider I tried to install your v13 branch of both extensions. Unfortunately the requirements are wrong (as far as I can tell). The requirement in `composer.json`of this extension should be

```json
"waldhacker/typo3-oauth2-client": "dev-feature/v12-compatibility-1 || v13.x-dev",
```

The [composer docs](https://getcomposer.org/doc/articles/versions.md) say:

> When branch names look like versions, we have to clarify for Composer that we're trying to check out a branch and not a tag. In the above example, we have two version branches: v1 and v2. To get Composer to check out one of these branches, you must specify a version constraint that looks like this: v1.x-dev. The .x is an arbitrary string that Composer requires to tell it that we're talking about the v1 branch and not a v1 tag (alternatively, you can name the branch v1.x instead of v1). **In the case of a branch with a version-like name (v1, in this case), you append -dev as a suffix, rather than using dev- as a prefix.**

Took me a bit to figure this out 😉
