### ISSUE TITLE
Undefined array key "slug" fe_users

### ISSUE THREAD

**Issue by abvdveen** [xima-media/xima-oauth2-extended#25]
When login in to Azure I get the error Undefined array key "slug" in typo3conf/ext/xima_oauth2_extended/Classes/UserFactory/FrontendUserFactory.php line 116

**Comment by maikschneider** [comment]
Hey @abvdveen, thanks for reporting! The fix is on the way.

**Comment by abvdveen** [comment]
@maikschneider Thanks for the fast response! Could you publish a new release that has this included?

**Comment by maikschneider** [comment]
Yes, just released [v2.0.3](https://github.com/xima-media/xima-oauth2-extended/releases/tag/v2.0.3)

**Comment by abvdveen** [comment]
@maikschneider Thanks!
